#!/usr/bin/env python3
"""
build_owtrad_trunk.py
=====================
Build a curated Silk Road *trunk* polyline from OWTRAD node names.

All waypoints are taken verbatim from data/store/silk_road/owtrad_nodes.csv,
which was generated by fetch_owtrad_silk_road.py from the OWTRAD-GIS datasets:

  Ciolek, T.M. (2004+). Old World Trade Routes (OWTRAD) Project.
  www.ciolek.com/owtrad.html — Canberra: Asia Pacific Research Online.
  Datasets used:
    tmcZCAm1000  Central Asia 1–1400 CE
    tmcIRa0100   Iran/Persia 50 BCE–300 CE
    tmcCNm1000   NW China 100–1400 CE
    tmcKGa0100d  Kyrgyzstan 100 BCE–1400 CE
  Licence: Open Publication License v1.0

The Levant anchor point (Mt. Gerizim) is the only non-OWTRAD coordinate;
it is the study's pre-registered anchor (35.274°E, 32.199°N).

OUTPUT
------
  data/store/silk_road/overland_trunk.csv
    Columns: route, order, lon, lat, name, dataset, owtrad_node_id

ROUTES
------
  north — main corridor: Levant → Palmyra → Mesopotamia → Iran →
           Merv → Bukhara → Samarkand → Kashgar → Northern Tarim →
           Dunhuang → Hexi → Chang'an
  south — southern branch: Merv → Herat → Balkh → Pamir →
           Kashgar → Khotan → Dunhuang (joins north at Dunhuang)

USAGE
-----
    python3 data/scripts/build_owtrad_trunk.py
"""

import csv
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT      = Path(__file__).resolve().parents[2]
NODES_CSV = ROOT / "data" / "store" / "silk_road" / "owtrad_nodes.csv"
OUT_CSV   = ROOT / "data" / "store" / "silk_road" / "overland_trunk.csv"

GERIZIM_LON, GERIZIM_LAT = 35.274, 32.199   # pre-registered anchor

# ── Trunk definition ──────────────────────────────────────────────────────────
# Each entry is (route, OWTRAD_name_or_None, dataset_hint, fallback_lon, fallback_lat, label)
# dataset_hint is used to disambiguate when the same name appears in multiple datasets.
# fallback coords are ONLY used for the Gerizim anchor (no OWTRAD node).
#
# Node names must match owtrad_nodes.csv column "name" exactly (case-sensitive).
# dataset_hint="" means accept any dataset.

TRUNK_SPEC = [
    # ── North branch ──────────────────────────────────────────────────────────
    # Levant anchor (non-OWTRAD)
    ("north", None,                  "",             GERIZIM_LON, GERIZIM_LAT, "Mt. Gerizim (study anchor)"),
    ("north", "Antioch",             "tmcIRa0100",   None, None, "Antioch / Antakya"),
    ("north", "Zeugma",              "tmcIRa0100",   None, None, "Zeugma (Euphrates crossing)"),
    ("north", "Palmyra",             "tmcIRa0100",   None, None, "Palmyra"),
    ("north", "Ctesiphon",           "tmcIRa0100",   None, None, "Ctesiphon / Seleucia (Mesopotamia)"),
    ("north", "Kermanshah",          "tmcIRa0100",   None, None, "Kermanshah"),
    ("north", "Hamadan",             "tmcZCAm1000",  None, None, "Hamadan / Ecbatana"),
    ("north", "Rhagae",              "tmcIRa0100",   None, None, "Rhagae / Rey (Tehran)"),
    ("north", "Meshed",              "tmcIRa0100",   None, None, "Meshed / Nishapur area"),
    ("north", "Marv",                "tmcZCAm1000",  None, None, "Merv"),
    ("north", "Bukhara",             "tmcZCAm1000",  None, None, "Bukhara"),
    ("north", "Samarkand",           "tmcKGa0100d",  None, None, "Samarkand"),
    ("north", "Taraz",               "tmcKGa0100d",  None, None, "Taraz / Jambul"),
    ("north", "Kashgar",             "tmcZCAm1000",  None, None, "Kashgar"),
    ("north", "Aksu",                "tmcZCAm1000",  None, None, "Aksu (N. Tarim)"),
    ("north", "Kucha",               "tmcZCAm1000",  None, None, "Kucha"),
    ("north", "Qara Shahr",          "tmcZCAm1000",  None, None, "Qara Shahr / Karashahr"),
    ("north", "Beshbaliq",           "tmcZCAm1000",  None, None, "Beshbaliq / Urumqi area"),
    ("north", "Qocho",               "tmcZCAm1000",  None, None, "Qocho / Turpan"),
    ("north", "Tun-huang",           "tmcZCAm1000",  None, None, "Dunhuang / Mogao"),
    ("north", "Ch'ang-an",           "tmcZCAm1000",  None, None, "Chang'an / Xi'an"),

    # ── South branch (Merv → Herat → Balkh → Pamir → Khotan → Dunhuang) ─────
    ("south", "Marv",                "tmcZCAm1000",  None, None, "Merv (junction)"),
    ("south", "Alexandria Areion",   "tmcIRa0100",   None, None, "Herat / Alexandria Areion"),
    ("south", "Balkh",               "tmcZCAm1000",  None, None, "Balkh / Bactra"),
    ("south", "Termez",              "tmcKGa0100d",  None, None, "Termez"),
    ("south", "Tashkurgan",          "tmcIRa0100",   None, None, "Tashkurgan (Pamir crossing)"),
    ("south", "Kashgar",             "tmcZCAm1000",  None, None, "Kashgar (junction)"),
    ("south", "Yarkand",             "tmcIRa0100",   None, None, "Yarkand"),
    ("south", "Khotan",              "tmcZCAm1000",  None, None, "Khotan"),
    ("south", "Lou-lan",             "tmcZCAm1000",  None, None, "Lop Nor / Lou-lan"),
    ("south", "Tun-huang",           "tmcZCAm1000",  None, None, "Dunhuang (joins north)"),
]


def load_nodes() -> dict:
    """Return dict keyed by (name, dataset) → (lon, lat, node_id)."""
    nodes = {}
    with open(NODES_CSV, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(r for r in f if not r.startswith("#")):
            try:
                lon = float(row["lon"])
                lat = float(row["lat"])
            except (ValueError, KeyError):
                continue
            key = (row["name"].strip(), row["dataset"].strip())
            nodes[key] = (lon, lat, row.get("node_id", ""))
    return nodes


def resolve(spec_name, dataset_hint, nodes):
    """Find (lon, lat, node_id, actual_dataset) for a given node name."""
    if spec_name is None:
        return None
    # Exact match with dataset hint
    if dataset_hint:
        key = (spec_name, dataset_hint)
        if key in nodes:
            lon, lat, nid = nodes[key]
            return lon, lat, nid, dataset_hint
    # Try any dataset
    for (name, ds), (lon, lat, nid) in nodes.items():
        if name == spec_name:
            return lon, lat, nid, ds
    return None


def main():
    print("Building OWTRAD-sourced overland trunk polyline...")
    nodes = load_nodes()

    rows = []
    order_by_route = {}
    errors = []

    for route, owtrad_name, dataset_hint, fb_lon, fb_lat, label in TRUNK_SPEC:
        order_by_route[route] = order_by_route.get(route, 0) + 1
        order = order_by_route[route]

        if owtrad_name is None:
            # Gerizim anchor — no OWTRAD node
            rows.append({
                "route": route, "order": order,
                "lon": fb_lon, "lat": fb_lat,
                "name": label,
                "dataset": "study_anchor",
                "owtrad_node_id": "",
            })
            print(f"  [{route}:{order:02d}] ★ {label}  ({fb_lon:.3f}, {fb_lat:.3f}) [anchor]")
            continue

        result = resolve(owtrad_name, dataset_hint, nodes)
        if result is None:
            errors.append(f"NOT FOUND: '{owtrad_name}' (hint={dataset_hint})")
            print(f"  [{route}:{order:02d}] ✗ {owtrad_name} — NOT FOUND")
            continue

        lon, lat, nid, ds = result
        rows.append({
            "route": route, "order": order,
            "lon": lon, "lat": lat,
            "name": label,
            "dataset": ds,
            "owtrad_node_id": nid,
        })
        print(f"  [{route}:{order:02d}] ✓ {label}  ({lon:.3f}, {lat:.3f}) [{ds} #{nid}]")

    if errors:
        print("\nERRORS — missing nodes:")
        for e in errors:
            print(f"  {e}")
        sys.exit(1)

    # Write output
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        f.write("# overland_trunk.csv — OWTRAD-sourced overland Silk Road trunk polyline\n")
        f.write("# DO NOT HAND-EDIT. Regenerate: python3 data/scripts/build_owtrad_trunk.py\n")
        f.write(f"# Generated: {ts}\n")
        f.write("#\n")
        f.write("# SOURCE: All waypoints from OWTRAD-GIS datasets (Ciolek 2004+).\n")
        f.write("#   Ciolek, T.M. (2004+). Old World Trade Routes (OWTRAD) Project.\n")
        f.write("#   www.ciolek.com/owtrad.html  Canberra: Asia Pacific Research Online.\n")
        f.write("#   Licence: Open Publication License v1.0\n")
        f.write("#   Datasets: tmcZCAm1000, tmcIRa0100, tmcCNm1000, tmcKGa0100d\n")
        f.write("# Exception: Mt. Gerizim (dataset=study_anchor) is the pre-registered\n")
        f.write("#   study anchor (35.274°E, 32.199°N), not an OWTRAD node.\n")
        f.write("#\n")
        f.write("# Columns: route, order, lon, lat, name, dataset, owtrad_node_id\n")
        writer = csv.DictWriter(f, fieldnames=["route","order","lon","lat","name","dataset","owtrad_node_id"])
        writer.writeheader()
        writer.writerows(rows)

    print(f"\n  ✓ Wrote {len(rows)} waypoints → {OUT_CSV}")
    north = sum(1 for r in rows if r["route"] == "north")
    south = sum(1 for r in rows if r["route"] == "south")
    print(f"    north branch: {north} nodes  |  south branch: {south} nodes")


if __name__ == "__main__":
    main()
